export const PIZZAS_RETRIEVED = 'PIZZAS_RETRIEVED';
export const PIZZA_TOPPINGS_RETRIEVED = 'PIZZA_TOPPINGS_RETRIEVED';
export const PIZZA_REMOVED = 'PIZZA_REMOVED';
export const PIZZA_CREATED = 'PIZZA_CREATED';
export const TOPPING_ADDED_TO_PIZZA = 'TOPPING_ADDED_TO_PIZZA';
export const TOPPING_REMOVED_FROM_PIZZA = 'TOPPING_REMOVED_FROM_PIZZA';

export const TOPPINGS_RETRIEVED = 'TOPPINGS_RETRIEVED';
export const TOPPING_CREATED = 'TOPPING_CREATED';
export const TOPPING_REMOVED = 'TOPPING_REMOVED';

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_COMPLETE = 'FETCHING_DATA_COMPLETE';

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const NOTIFICATION_DISMISSED = 'NOTIFICATION_DISMISSED';
